<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ConfigSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        \Illuminate\Support\Facades\DB::table('configs')->truncate();
        \Illuminate\Support\Facades\DB::table('configs')->insert([
            [
                'id' => 1,
                'contactUsPage' => '<p style="text-align:center"><span style="font-size:36px"><strong>Li&ecirc;n hệ</strong></span></p>

<p style="text-align:center"><span style="font-size:18px">Để kh&ocirc;ng ngừng n&acirc;ng cao chất lượng dịch vụ v&agrave; đ&aacute;p ứng tốt hơn nữa c&aacute;c y&ecirc;u cầu của Qu&yacute; kh&aacute;ch, ch&uacute;ng t&ocirc;i mong muốn nhận được c&aacute;c th&ocirc;ng tin phản hồi. Nếu Qu&yacute; kh&aacute;ch c&oacute; bất kỳ thắc mắc hoặc đ&oacute;ng g&oacute;p n&agrave;o, xin vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i theo th&ocirc;ng tin dưới đ&acirc;y. Ch&uacute;ng t&ocirc;i sẽ phản hồi lại Qu&yacute; kh&aacute;ch trong thời gian sớm nhất.</span></p>
',
                'aboutUsPage' => '<h3><span style="font-size:22px">Giới thiệu</span></h3>

<p>&nbsp;</p>

<h2><span style="font-size:22px"><strong>Lịch sử ra đời DoiDoSBTC.vn</strong></span></h2>

<p>&nbsp;</p>

<p><span style="font-size:14px">DoiDo.vn ra đời khi 5 người gặp nhau gồm&nbsp;<strong>Nguyễn Minh T&uacute;,&nbsp;Trần Anh Đức,&nbsp;Nguyễn Quang Huy,&nbsp;Đinh Mạnh Tr&iacute;,&nbsp;Điều Huy Ph&uacute;c</strong> . Cả 5 c&ugrave;ng c&oacute; &yacute; tưởng trước đ&oacute; về một trang web để mọi người c&oacute; thể trao đổi những m&oacute;n đồ kh&ocirc;ng d&ugrave;ng đến với nhau m&agrave; kh&ocirc;ng mất tiền, rất nhanh sau đ&oacute;, trang web DoiDoSBTC.vn được sinh ra đời.</span></p>

<p>&nbsp;</p>

<h2><span style="font-size:22px"><strong>DoiDoSBTC.vn l&agrave; g&igrave;?</strong></span></h2>

<p>&nbsp;</p>

<p><span style="font-size:14px">DoiDoSBTC.vn l&agrave; s&agrave;n trao đổi đồ ngang h&agrave;ng, kh&ocirc;ng d&ugrave;ng tiền mặt, th&agrave;nh vi&ecirc;n c&oacute; thể trao đổi bất kỳ m&oacute;n đồ n&agrave;o m&agrave; m&igrave;nh đang sở hữu. Mỗi th&agrave;nh vi&ecirc;n chỉ việc đăng m&oacute;n đồ của m&igrave;nh l&ecirc;n v&agrave; c&oacute; th&agrave;nh vi&ecirc;n kh&aacute;c th&iacute;ch m&oacute;n đồ của m&igrave;nh, cả hai c&ugrave;ng thực hiện lệnh đổi đồ cho nhau. L&uacute;c n&agrave;y, hệ thống ghi nhận cả 2 đ&atilde; thực hiện việc đổi đồ cho nhau, cả hai tự sắp xếp hẹn nhau ngo&agrave;i đời để trao đổi, khi trao đổi xong sẽ l&ecirc;n website x&aacute;c nhận lại với hệ thống bằng những h&igrave;nh ảnh đ&atilde; chụp v&agrave; nhận điểm (số điểm n&agrave;y c&oacute; thể t&iacute;ch lũy để đổi qu&agrave;).</span></p>

<p>&nbsp;</p>

<h2><span style="font-size:22px"><strong>Tại sao KH&Ocirc;NG tiền mặt?</strong></span></h2>

<p>&nbsp;</p>

<p><span style="font-size:14px">Ch&uacute;ng t&ocirc;i nhận thấy rằng, tiền tệ c&oacute; 2 mặt của n&oacute;. Mặt tốt gi&uacute;p mọi người c&oacute; thể chi ti&ecirc;u v&agrave; trao đổi những c&aacute;i m&igrave;nh muốn; mặt kh&aacute;c, tiền l&agrave;m con người bị lệ thuộc v&agrave;o n&oacute;, từ đ&acirc;y mọi người h&agrave;nh động bất chấp để c&oacute; tiền, v&agrave; từ đ&acirc;y bắt đầu sinh ra nhiều hệ lụy. Vậy giải ph&aacute;p n&agrave;o để con người đạt được c&aacute;i họ muốn m&agrave; kh&ocirc;ng cần d&ugrave;ng đến tiền? C&acirc;u trả lời ch&iacute;nh l&agrave;:<strong>&nbsp;barter trade</strong>&nbsp;-<strong>&nbsp;trao đổi ngang h&agrave;ng.</strong></span></p>

<p>&nbsp;</p>

<h2><span style="font-size:22px"><strong>Sứ mệnh của DoiDoSBTC.vn</strong></span></h2>

<p>&nbsp;</p>

<p><span style="font-size:14px">- Ph&aacute;t triển s&agrave;n đổi đồ ngang h&agrave;ng (barter trade) lớn nhất Việt Nam.<br />
- Chung tay bảo vệ m&ocirc;i trường bằng c&aacute;ch t&aacute;i sử dụng những m&oacute;n đồ cũ, hạn chế thải r&aacute;c ra m&ocirc;i trường.<br />
- Nơi mọi người c&oacute; thể thực h&agrave;nh việc &quot;Cho - Nhận&quot; xuất ph&aacute;t từ đ&aacute;y l&ograve;ng, một c&aacute;ch ch&acirc;n thật nhất.<br />
- Nơi giao lưu, kết bạn đ&uacute;ng nghĩa.</span></p>
',
                'policyPage'=>'',
//                'policyPage' => '<p style="text-align:center">Chỉnh sửa trang policy</p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>1.</strong><strong>&nbsp;</strong><strong>GIỚI THIỆU</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">1.1. Ch&agrave;o mừng bạn đến với nền tảng Shopee.vn (bao gồm website&nbsp;<a href="http://shopee.vn/" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>http://doido.vn</u></a>&nbsp;) được được vận h&agrave;nh bởi C&ocirc;ng ty TNHH SBTC v&agrave; c&aacute;c c&ocirc;ng ty li&ecirc;n kết (gọi ri&ecirc;ng v&agrave; gọi chung l&agrave;, &quot;Doido&quot;, &quot;ch&uacute;ng t&ocirc;i&quot;, hay &quot;của ch&uacute;ng t&ocirc;i&quot;). Shopee nghi&ecirc;m t&uacute;c thực hiện tr&aacute;ch nhiệm của m&igrave;nh li&ecirc;n quan đến bảo mật th&ocirc;ng tin theo c&aacute;c quy định về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n của ph&aacute;p luật Việt Nam (&ldquo;Luật ri&ecirc;ng tư&rdquo;) v&agrave; cam kết t&ocirc;n trọng quyền ri&ecirc;ng tư v&agrave; sự quan t&acirc;m của tất cả người d&ugrave;ng đối với c&aacute;c nền tảng Shopee (&ldquo;Nền tảng&rdquo;) (ch&uacute;ng t&ocirc;i gọi chung C&aacute;c Nền tảng v&agrave; c&aacute;c dịch vụ ch&uacute;ng t&ocirc;i cung cấp như được m&ocirc; tả trong Nền tảng của ch&uacute;ng t&ocirc;i l&agrave; &quot;C&aacute;c Dịch Vụ&quot;). Ch&uacute;ng t&ocirc;i nhận biết tầm quan trọng của dữ liệu c&aacute; nh&acirc;n m&agrave; bạn đ&atilde; tin tưởng giao cho ch&uacute;ng t&ocirc;i v&agrave; tin rằng ch&uacute;ng t&ocirc;i c&oacute; tr&aacute;ch nhiệm quản l&yacute;, bảo vệ v&agrave; xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn một c&aacute;ch th&iacute;ch hợp. Ch&iacute;nh s&aacute;ch bảo mật n&agrave;y (&quot;Ch&iacute;nh s&aacute;ch bảo mật&quot; hay &quot;Ch&iacute;nh s&aacute;ch&quot;) được thiết kế để gi&uacute;p bạn hiểu được c&aacute;ch thức ch&uacute;ng t&ocirc;i thu thập, sử dụng, tiết lộ v&agrave;/hoặc xử l&yacute; dữ liệu c&aacute; nh&acirc;n m&agrave; bạn đ&atilde; cung cấp cho ch&uacute;ng t&ocirc;i v&agrave;/hoặc lưu giữ về bạn, cho d&ugrave; l&agrave; hiện nay hoặc trong tương lai, cũng như để gi&uacute;p bạn đưa ra quyết định s&aacute;ng suốt trước khi cung cấp cho ch&uacute;ng t&ocirc;i bất kỳ dữ liệu c&aacute; nh&acirc;n n&agrave;o của bạn.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">1.2. &quot;Dữ Liệu C&aacute; Nh&acirc;n&quot; hay &quot;dữ liệu c&aacute; nh&acirc;n&quot; c&oacute; nghĩa l&agrave; dữ liệu, d&ugrave; đ&uacute;ng hay kh&ocirc;ng, về một c&aacute; nh&acirc;n m&agrave; th&ocirc;ng qua đ&oacute; c&oacute; thể được x&aacute;c định được danh t&iacute;nh, hoặc từ dữ liệu đ&oacute; v&agrave; th&ocirc;ng tin kh&aacute;c m&agrave; một tổ chức c&oacute; hoặc c&oacute; khả năng tiếp cận. C&aacute;c v&iacute; dụ thường gặp về dữ liệu c&aacute; nh&acirc;n c&oacute; thể gồm c&oacute; t&ecirc;n, số chứng minh nh&acirc;n d&acirc;n v&agrave; th&ocirc;ng tin li&ecirc;n hệ.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">1.3. Bằng việc sử dụng C&aacute;c Dịch Vụ, đăng k&yacute; một t&agrave;i khoản với ch&uacute;ng t&ocirc;i hoặc truy cập Nền tảng, bạn x&aacute;c nhận v&agrave; đồng &yacute; rằng bạn chấp nhận c&aacute;c phương ph&aacute;p, y&ecirc;u cầu, v&agrave;/hoặc ch&iacute;nh s&aacute;ch được m&ocirc; tả trong Ch&iacute;nh s&aacute;ch bảo mật n&agrave;y, v&agrave; theo đ&acirc;y bạn đồng &yacute; cho ph&eacute;p ch&uacute;ng t&ocirc;i thu thập, sử dụng, tiết lộ v&agrave;/hoặc xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn như m&ocirc; tả trong đ&acirc;y. NẾU BẠN KH&Ocirc;NG ĐỒNG &Yacute; CHO PH&Eacute;P XỬ L&Yacute; DỮ LIỆU C&Aacute; NH&Acirc;N CỦA BẠN NHƯ M&Ocirc; TẢ TRONG CH&Iacute;NH S&Aacute;CH N&Agrave;Y, VUI L&Ograve;NG KH&Ocirc;NG SỬ DỤNG C&Aacute;C DỊCH VỤ CỦA CH&Uacute;NG T&Ocirc;I HAY TRUY CẬP NỀN TẢNG HOẶC TRANG WEB CỦA CH&Uacute;NG T&Ocirc;I. Nếu ch&uacute;ng t&ocirc;i thay đổi Ch&iacute;nh s&aacute;ch bảo mật của m&igrave;nh, ch&uacute;ng t&ocirc;i sẽ đăng những thay đổi đ&oacute; hoặc Ch&iacute;nh s&aacute;ch bảo mật sửa đổi tr&ecirc;n Nền tảng của ch&uacute;ng t&ocirc;i.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>2.</strong><strong>&nbsp;</strong><strong>KHI N&Agrave;O DOIDOSẼ THU THẬP DỮ LIỆU C&Aacute; NH&Acirc;N?</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">2.1. Ch&uacute;ng t&ocirc;i sẽ/c&oacute; thể thu thập dữ liệu c&aacute; nh&acirc;n về bạn:</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">a. khi bạn đăng k&yacute; v&agrave;/hoặc sử dụng C&aacute;c Dịch Vụ hoặc Nền tảng của ch&uacute;ng t&ocirc;i, hoặc mở một t&agrave;i khoản với ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">b. khi bạn gửi bất kỳ biểu mẫu n&agrave;o, bao gồm đơn đăng k&yacute; hoặc c&aacute;c mẫu đơn kh&aacute;c li&ecirc;n quan đến bất kỳ sản phẩm v&agrave; dịch vụ n&agrave;o của ch&uacute;ng t&ocirc;i, bằng h&igrave;nh thức trực tuyến hay dưới h&igrave;nh thức kh&aacute;c;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">c. khi bạn k&yacute; kết bất kỳ thỏa thuận n&agrave;o hoặc cung cấp c&aacute;c t&agrave;i liệu hoặc th&ocirc;ng tin kh&aacute;c li&ecirc;n quan đến tương t&aacute;c giữa bạn với ch&uacute;ng t&ocirc;i, hoặc khi bạn sử dụng c&aacute;c sản phẩm v&agrave; dịch vụ của ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">d. khi bạn tương t&aacute;c với ch&uacute;ng t&ocirc;i, chẳng hạn như th&ocirc;ng qua c&aacute;c cuộc gọi điện thoại (c&oacute; thể được ghi &acirc;m lại), thư từ, fax, gặp gỡ trực tiếp, c&aacute;c nền ứng dụng truyền th&ocirc;ng x&atilde; hội v&agrave; email;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">e. khi bạn sử dụng c&aacute;c dịch vụ điện tử của ch&uacute;ng t&ocirc;i, hoặc tương t&aacute;c với ch&uacute;ng t&ocirc;i qua Nền tảng hoặc Trang Web hoặc C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i. Trường hợp n&agrave;y bao gồm th&ocirc;ng qua tập tin cookie m&agrave; ch&uacute;ng t&ocirc;i c&oacute; thể triển khai khi bạn tương t&aacute;c với c&aacute;c Nền tảng hoặc Trang Web của ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">f. khi bạn thực hiện c&aacute;c giao dịch th&ocirc;ng qua Dịch vụ của ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">g. khi bạn cung cấp &yacute; kiến phản hồi hoặc gửi khiếu nại cho ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">h. khi bạn đăng k&yacute; tham gia một cuộc thi;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">i. khi bạn gửi dữ liệu c&aacute; nh&acirc;n của bạn cho ch&uacute;ng t&ocirc;i v&igrave; bất kỳ l&yacute; do g&igrave;.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>3.</strong><strong>&nbsp;DOIDO</strong><strong>SẼ THU THẬP NHỮNG DỮ LIỆU G&Igrave;?</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">3.1. Dữ liệu c&aacute; nh&acirc;n m&agrave; Shopee c&oacute; thể thu thập bao gồm:</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">a. họ t&ecirc;n;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">b. địa chỉ email;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">c. ng&agrave;y sinh;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">d. địa chỉ thanh to&aacute;n;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">e. t&agrave;i khoản ng&acirc;n h&agrave;ng v&agrave; th&ocirc;ng tin thanh to&aacute;n;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">f. số điện thoại;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">g. giới t&iacute;nh;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">h. Th&ocirc;ng tin được gửi bởi hoặc li&ecirc;n quan đến (c&aacute;c) thiết bị được sử dụng để truy cập v&agrave;o C&aacute;c Dịch vụ hoặc Nền tảng của ch&uacute;ng t&ocirc;i.</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">i. bất kỳ th&ocirc;ng tin n&agrave;o kh&aacute;c về người d&ugrave;ng khi người d&ugrave;ng đăng nhập để sử dụng C&aacute;c Dịch Vụ hoặc Nền tảng của ch&uacute;ng t&ocirc;i, v&agrave; khi người d&ugrave;ng sử dụng C&aacute;c Dịch Vụ hoặc Nền tảng, cũng như th&ocirc;ng tin về việc người d&ugrave;ng sử dụng C&aacute;c Dịch Vụ hoặc Nền tảng của ch&uacute;ng t&ocirc;i như thế n&agrave;o; v&agrave;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">j. dữ liệu tổng hợp về nội dung người d&ugrave;ng sử dụng.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">3.2. Bạn đồng &yacute; kh&ocirc;ng cung cấp cho ch&uacute;ng t&ocirc;i bất cứ th&ocirc;ng tin n&agrave;o kh&ocirc;ng ch&iacute;nh x&aacute;c hoặc g&acirc;y hiểu nhầm v&agrave; bạn đồng &yacute; sẽ th&ocirc;ng b&aacute;o cho ch&uacute;ng t&ocirc;i về bất cứ th&ocirc;ng tin n&agrave;o kh&ocirc;ng ch&iacute;nh x&aacute;c hoặc khi c&oacute; sự thay đổi th&ocirc;ng tin. Ch&uacute;ng t&ocirc;i bảo lưu quyền theo quyết định ri&ecirc;ng của ch&uacute;ng t&ocirc;i được y&ecirc;u cầu c&aacute;c t&agrave;i liệu cần thiết kh&aacute;c để x&aacute;c minh th&ocirc;ng tin được bạn cung cấp.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">3.3. Nếu bạn đăng nhập để trở th&agrave;nh Người sử dụng c&aacute;c Nền tảng của ch&uacute;ng t&ocirc;i sử dụng t&agrave;i khoản mạng x&atilde; hội của Bạn (&ldquo;T&agrave;i khoản Mạng X&atilde; hội&rdquo;), li&ecirc;n kết t&agrave;i khoản của bạn với T&agrave;i khoản Mạng X&atilde; hội của bạn hoặc sử dụng bất cứ t&iacute;nh năng mạng x&atilde; hội Shopee n&agrave;o, ch&uacute;ng t&ocirc;i c&oacute; quyền truy cập th&ocirc;ng tin về bạn m&agrave; bạn đ&atilde; cung cấp một c&aacute;ch tự nguy&ecirc;n cho nh&agrave; cung cấp dịch vụ T&agrave;i khoản Mạng X&atilde; hội của Bạn tu&acirc;n theo c&aacute;c ch&iacute;nh s&aacute;ch của c&aacute;c nh&agrave; cung cấp dịch vụ n&agrave;y, v&agrave; ch&uacute;ng t&ocirc;i sẽ quản l&yacute; v&agrave; sử dụng c&aacute;c dữ liệu c&aacute; nh&acirc;n n&agrave;y của bạn theo c&aacute;c quy định của Ch&iacute;nh s&aacute;ch n&agrave;y tại mọi thời điểm.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">3.4. Nếu bạn kh&ocirc;ng muốn ch&uacute;ng t&ocirc;i thu thập th&ocirc;ng tin/dữ liệu c&aacute; nh&acirc;n n&oacute;i tr&ecirc;n, bạn c&oacute; thể chọn kh&ocirc;ng tham gia v&agrave;o bất kỳ l&uacute;c n&agrave;o bằng c&aacute;ch th&ocirc;ng b&aacute;o bằng văn bản đến Nh&acirc;n Vi&ecirc;n Bảo Vệ Dữ Liệu của ch&uacute;ng t&ocirc;i. C&oacute; thể t&igrave;m thấy th&ecirc;m th&ocirc;ng tin về nội dung trong mục &quot;Bạn c&oacute; thể r&uacute;t lại sự cho ph&eacute;p x&oacute;a t&ecirc;n, y&ecirc;u cầu truy cập hoặc điều chỉnh th&ocirc;ng tin bạn đ&atilde; cung cấp cho ch&uacute;ng t&ocirc;i bằng c&aacute;ch n&agrave;o?&quot; dưới đ&acirc;y. Tuy nhi&ecirc;n, lưu &yacute; rằng việc từ chối hoặc hủy bỏ cho ph&eacute;p ch&uacute;ng t&ocirc;i thu thập, sử dụng hoặc xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn c&oacute; thể ảnh hưởng đến việc bạn sử dụng C&aacute;c Dịch Vụ v&agrave; Nền tảng. V&iacute; dụ như dịch vụ x&aacute;c định vị tr&iacute; sẽ kh&ocirc;ng hoạt động nếu bạn kh&ocirc;ng cho ph&eacute;p ứng dụng truy cập vị tr&iacute; của bạn</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>4.</strong><strong>&nbsp;</strong><strong>THU THẬP C&Aacute;C DỮ LIỆU KH&Aacute;C</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">4.1.<strong>&nbsp;</strong>Như với hầu hết c&aacute;c trang web v&agrave; c&aacute;c ứng dụng di động kh&aacute;c, thiết bị của bạn gửi th&ocirc;ng tin c&oacute; thể gồm c&oacute; dữ liệu về bạn, được một m&aacute;y chủ web ghi lại khi bạn sử dụng Nền tảng của ch&uacute;ng t&ocirc;i. Th&ocirc;ng tin n&agrave;y bao gồm địa chỉ IP, hệ điều h&agrave;nh của m&aacute;y t&iacute;nh/thiết bị di động, loại tr&igrave;nh duyệt, loại thiết bị di động, c&aacute;c đặc điểm của thiết bị di động, m&atilde; định danh thiết bị thống nhất (UDID) hoặc m&atilde; định danh thiết bị di động (MEID) của thiết bị di động của bạn, địa chỉ tham chiếu của Trang Web (nếu c&oacute;), c&aacute;c trang m&agrave; bạn đ&atilde; truy cập đến tr&ecirc;n trang web hoặc ứng dụng di động của ch&uacute;ng t&ocirc;i v&agrave; thời gian truy cập v&agrave; đ&ocirc;i khi l&agrave; &quot;cookie&quot; (c&oacute; thể v&ocirc; hiệu h&oacute;a bằng c&aacute;ch sử dụng t&ugrave;y chọn tr&igrave;nh duyệt của bạn) để gi&uacute;p trang web ghi nhớ lần truy cập cuối c&ugrave;ng của bạn. Nếu bạn đăng nhập, th&ocirc;ng tin n&agrave;y được li&ecirc;n kết với t&agrave;i khoản c&aacute; nh&acirc;n của bạn. Th&ocirc;ng tin n&agrave;y cũng được đưa v&agrave;o c&aacute;c số liệu thống k&ecirc; ẩn danh để gi&uacute;p ch&uacute;ng t&ocirc;i hiểu được kh&aacute;ch truy cập sử dụng Trang Web của ch&uacute;ng t&ocirc;i như thế n&agrave;o.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">4.2. C&aacute;c ứng dụng di động của ch&uacute;ng t&ocirc;i c&oacute; thể thu thập th&ocirc;ng tin ch&iacute;nh x&aacute;c về địa chỉ của thiết bị di động của bạn sử dụng c&aacute;c c&ocirc;ng nghệ như GPS, Wi-Fi,&hellip;. Ch&uacute;ng t&ocirc;i thu thập, sử dụng, c&ocirc;ng bố v&agrave;/hoặc xử l&yacute; c&aacute;c th&ocirc;ng tin n&agrave;y cho một hoặc nhiều mục đ&iacute;ch bao gồm c&aacute;c dịch vụ được cung cấp dựa tr&ecirc;n vị tr&iacute; m&agrave; bạn y&ecirc;u cầu hoặc chuyển c&aacute;c nội dung c&oacute; li&ecirc;n quan đến bạn dựa tr&ecirc;n vị tr&iacute; của bạn hoặc cho ph&eacute;p bạn chia sẻ vị tr&iacute; của bạn cho c&aacute;c Người sử dụng kh&aacute;c như l&agrave; một phần của c&aacute;c Dịch vụ được cung cấp bởi c&aacute;c ứng dụng di động của ch&uacute;ng t&ocirc;i. Đối với phần lớn c&aacute;c thiết bị di động, bạn c&oacute; thể r&uacute;t lại sự cho ph&eacute;p để ch&uacute;ng t&ocirc;i được thu thập c&aacute;c th&ocirc;ng tin n&agrave;y dựa tr&ecirc;n vị tr&iacute; của bạn th&ocirc;ng qua c&aacute;c c&agrave;i đặt tr&ecirc;n thiết bị. Nếu bạn c&oacute; c&acirc;u hỏi n&agrave;o về c&aacute;ch thức v&ocirc; hiệu h&oacute;a c&aacute;c dịch vụ vị tr&iacute; tr&ecirc;n thiết bị di động của bạn, vui l&ograve;ng li&ecirc;n hệ với c&aacute;c nh&agrave; cung cấp dịch vụ thiết bị di động hoặc nh&agrave; sản xuất thiết bị của bạn.&nbsp;</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>5.</strong><strong>&nbsp;</strong><strong>COOKIES</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">5.1. Đ&ocirc;i khi ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng &quot;cookie&quot; hoặc c&aacute;c t&iacute;nh năng kh&aacute;c để cho ph&eacute;p ch&uacute;ng t&ocirc;i hoặc c&aacute;c b&ecirc;n thứ ba thu thập hoặc chia sẻ th&ocirc;ng tin sẽ gi&uacute;p ch&uacute;ng t&ocirc;i cải thiện Nền tảng của m&igrave;nh v&agrave; C&aacute;c Dịch Vụ ch&uacute;ng t&ocirc;i cung cấp, hoặc gi&uacute;p ch&uacute;ng t&ocirc;i đưa ra c&aacute;c dịch vụ v&agrave; t&iacute;nh năng mới. &quot;Cookie&quot; l&agrave; c&aacute;c m&atilde; danh định ch&uacute;ng t&ocirc;i gửi đến m&aacute;y t&iacute;nh hoặc thiết bị di động của bạn, cho ph&eacute;p ch&uacute;ng t&ocirc;i nhận dạng m&aacute;y t&iacute;nh hoặc thiết bị của bạn v&agrave; cho ch&uacute;ng t&ocirc;i biết khi n&agrave;o C&aacute;c Dịch Vụ hoặc Nền tảng được sử dụng hay truy cập, bởi bao nhi&ecirc;u người v&agrave; để theo d&otilde;i những hoạt động trong C&aacute;c Nền tảng của ch&uacute;ng t&ocirc;i. Ch&uacute;ng t&ocirc;i c&oacute; thể li&ecirc;n kết th&ocirc;ng tin cookie với dữ liệu c&aacute; nh&acirc;n. Cookie cũng li&ecirc;n kết với th&ocirc;ng tin về những nội dung bạn đ&atilde; chọn đối với c&aacute;c trang mua sắm bạn đ&atilde; xem, hoặc c&aacute;c game bạn đ&atilde; chơi. Th&ocirc;ng tin n&agrave;y được sử dụng để v&iacute; dụ như theo d&otilde;i giỏ h&agrave;ng. Cookie cũng được sử dụng để cung cấp nội dung dựa tr&ecirc;n quan t&acirc;m của bạn v&agrave; để theo d&otilde;i việc sử dụng của c&aacute;c Dịch Vụ.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">5.2. Bạn c&oacute; thể từ chối sử dụng cookie bằng c&aacute;ch chọn c&aacute;c thiết lập th&iacute;ch hợp tr&ecirc;n tr&igrave;nh duyệt của bạn. Tuy nhi&ecirc;n, vui l&ograve;ng lưu &yacute; rằng nếu bạn thực hiện thao t&aacute;c n&agrave;y bạn c&oacute; thể kh&ocirc;ng sử dụng được c&aacute;c chức năng đầy đủ của Nền tảng hoặc C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>6.</strong><strong>&nbsp;</strong><strong>XEM V&Agrave; TẢI C&Aacute;C NỘI DUNG V&Agrave; QUẢNG C&Aacute;O</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">6.1. Do khi bạn xem c&aacute;c trang tr&ecirc;n trang web hoặc ứng dụng di động của ch&uacute;ng t&ocirc;i, khi bạn xem c&aacute;c nội dung v&agrave; quảng c&aacute;o v&agrave; truy cập v&agrave;o c&aacute;c phần mềm kh&aacute;c tr&ecirc;n Nền tảng của ch&uacute;ng t&ocirc;i hoặc th&ocirc;ng qua Dịch vụ, phần lớn c&aacute;c th&ocirc;ng tin giống nhau sẽ được gửi đến cho ch&uacute;ng t&ocirc;i (bao gồm địa chỉ IP, hệ điều h&agrave;nh, v.v&hellip;); nhưng, thay v&igrave; c&aacute;c lượt xem trang, thiết bị của bạn gửi đến ch&uacute;ng t&ocirc;i th&ocirc;ng tin về c&aacute;c nội dung, quảng c&aacute;o được xem v&agrave;/hoặc phần mềm được c&agrave;i đặt tr&ecirc;n c&aacute;c Dịch vụ v&agrave; Nền tảng v&agrave; thời gian.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>7.</strong><strong>&nbsp;</strong><strong>CH&Uacute;NG T&Ocirc;I SỬ DỤNG TH&Ocirc;NG TIN BẠN CUNG CẤP CHO CH&Uacute;NG T&Ocirc;I NHƯ THẾ N&Agrave;O?</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">7.1. Ch&uacute;ng t&ocirc;i c&oacute; thể thu thập, sử dụng, tiết lộ v&agrave;/hoặc xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn cho các mục đích sau đ&acirc;y:</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">a. để xem x&eacute;t v&agrave;/hoặc xử l&yacute; đơn đăng k&yacute;/giao dịch của bạn với ch&uacute;ng t&ocirc;i hoặc giao dịch hay thư từ của bạn với c&aacute;c b&ecirc;n thứ ba qua C&aacute;c Dịch Vụ;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">b. để quản l&yacute;, điều h&agrave;nh, cung cấp v&agrave;/hoặc quản l&yacute; việc bạn sử dụng v&agrave;/hoặc truy cập C&aacute;c Dịch Vụ v&agrave; c&aacute;c Nền tảng của ch&uacute;ng t&ocirc;i (bao gồm c&aacute;c sở th&iacute;ch của bạn), cũng như quan hệ v&agrave; t&agrave;i khoản người d&ugrave;ng của bạn với ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">c. để đ&aacute;p ứng, xử l&yacute;, giải quyết hoặc ho&agrave;n tất một giao dịch v&agrave;/hoặc đ&aacute;p ứng c&aacute;c y&ecirc;u cầu của bạn đối với c&aacute;c sản phẩm v&agrave; dịch vụ nhất định v&agrave; th&ocirc;ng b&aacute;o cho bạn về c&aacute;c vấn đề dịch vụ v&agrave; c&aacute;c hoạt động t&agrave;i khoản bất thường;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">d. để thực thi c&aacute;c Điều Khoản Dịch Vụ của ch&uacute;ng t&ocirc;i hoặc bất kỳ thỏa thuận giấy ph&eacute;p người d&ugrave;ng cuối n&agrave;o &aacute;p dụng;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">e. để bảo vệ sự an to&agrave;n c&aacute; nh&acirc;n v&agrave; c&aacute;c quyền, t&agrave;i sản hoặc sự an to&agrave;n của người kh&aacute;c;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">f. để nhận dạng v&agrave;/hoặc x&aacute;c minh;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">g. để duy tr&igrave; v&agrave; quản l&yacute; bất kỳ bản cập nhật phần mềm n&agrave;o v&agrave;/hoặc c&aacute;c bản cập nhật kh&aacute;c v&agrave; sự hỗ trợ c&oacute; thể được y&ecirc;u cầu t&ugrave;y l&uacute;c nhằm đảm bảo C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i hoạt động su&ocirc;n sẻ;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">h. để giải quyết hoặc tạo điều kiện dịch vụ kh&aacute;ch h&agrave;ng, thực hiện c&aacute;c chỉ thị của bạn, giải quyết hoặc trả lời bất kỳ thắc mắc n&agrave;o được gửi bởi (hoặc nhằm được gửi bởi) bạn hoặc thay mặt bạn;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">i. để li&ecirc;n hệ với bạn hoặc li&ecirc;n lạc với bạn qua điện thoại, tin nhắn văn bản v&agrave;/hoặc tin nhắn fax, email v&agrave;/hoặc thư hoặc c&aacute;ch kh&aacute;c nhằm mục đ&iacute;ch quản trị v&agrave;/hoặc quản l&yacute; quan hệ của bạn với ch&uacute;ng t&ocirc;i hoặc việc bạn sử dụng C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i, chẳng hạn như ở việc truyền đạt th&ocirc;ng tin h&agrave;nh ch&iacute;nh cho bạn li&ecirc;n quan đến C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i. Bạn x&aacute;c nhận v&agrave; đồng &yacute; rằng sự li&ecirc;n lạc như thế của ch&uacute;ng t&ocirc;i c&oacute; thể l&agrave; theo c&aacute;ch gửi thư qua đường bưu điện, t&agrave;i liệu hoặc th&ocirc;ng b&aacute;o cho bạn, c&oacute; thể gồm c&oacute; tiết lộ dữ liệu c&aacute; nh&acirc;n nhất định về bạn để cung cấp c&aacute;c t&agrave;i liệu đ&oacute; cũng như tr&ecirc;n bao b&igrave;/phong b&igrave;;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">j. để cho ph&eacute;p c&aacute;c người d&ugrave;ng kh&aacute;c tương t&aacute;c hoặc li&ecirc;n lạc với bạn th&ocirc;ng qua Nền tảng, bao gồm để th&ocirc;ng b&aacute;o cho bạn khi một người d&ugrave;ng kh&aacute;c đ&atilde; gửi cho bạn một tin nhắn ri&ecirc;ng tư hoặc đăng nhận x&eacute;t cho bạn tr&ecirc;n Nền tảng;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">k. để tiến h&agrave;nh c&aacute;c hoạt động nghi&ecirc;n cứu, ph&acirc;n t&iacute;ch v&agrave; ph&aacute;t triển (bao gồm ph&acirc;n t&iacute;ch dữ liệu, khảo s&aacute;t, ph&aacute;t triển v&agrave;/hoặc lập đặc t&iacute;nh sản phẩm v&agrave; dịch vụ), để ph&acirc;n t&iacute;ch c&aacute;ch thức bạn sử dụng C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i, để cải thiện C&aacute;c Dịch Vụ hoặc sản phẩm của ch&uacute;ng t&ocirc;i v&agrave;/hoặc để cải thiện trải nghiệm kh&aacute;ch h&agrave;ng của bạn;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">l. để cho ph&eacute;p quảng c&aacute;o v&agrave; c&aacute;c đợt kiểm tra v&agrave; khảo s&aacute;t kh&aacute;c, ngo&agrave;i những hoạt động kh&aacute;c, x&aacute;c thực quy m&ocirc; v&agrave; th&agrave;nh phần của đối tượng khảo s&aacute;t, v&agrave; hiểu được trải nghiệm của họ với C&aacute;c Dịch Vụ của Doido;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">m. v&igrave; mục đ&iacute;ch tiếp thị, trong trường hợp n&agrave;y, để gửi cho bạn qua c&aacute;c phương thức li&ecirc;n lạc kh&aacute;c nhau, th&ocirc;ng tin v&agrave; t&agrave;i liệu tiếp thị v&agrave; quảng b&aacute; li&ecirc;n quan đến c&aacute;c sản phẩm v&agrave;/hoặc dịch vụ (bao gồm c&aacute;c sản phẩm v&agrave;/hoặc dịch vụ của c&aacute;c b&ecirc;n thứ ba m&agrave; Shopee c&oacute; thể hợp t&aacute;c hoặc li&ecirc;n kết) c&oacute; thể b&aacute;n, tiếp thị hoặc quảng b&aacute;, cho d&ugrave; c&aacute;c sản phẩm hoặc dịch vụ đ&oacute; tồn tại v&agrave;o l&uacute;c n&agrave;y hoặc được tạo ra trong tương lai. Bạn c&oacute; thể hủy đăng k&yacute; nhận c&aacute;c th&ocirc;ng tin tiếp thị tại bất cứ thời điểm n&agrave;o bằng c&aacute;ch sử dụng chức năng hủy đăng k&yacute; trong c&aacute;c t&agrave;i liệu tiếp thị điện tử. Ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng c&aacute;c th&ocirc;ng tin li&ecirc;n hệ của bạn để gửi c&aacute;c bản tin từ ch&uacute;ng t&ocirc;i hoặc từ c&aacute;c c&ocirc;ng ty c&oacute; li&ecirc;n quan của ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">n. để đ&aacute;p ứng c&aacute;c thủ tục ph&aacute;p l&yacute; hoặc để tu&acirc;n thủ hoặc theo quy định của ph&aacute;p luật hiện h&agrave;nh, v&agrave; c&aacute;c y&ecirc;u cầu của cơ quan nh&agrave; nước c&oacute; thẩm quyền;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">o. để lập số liệu thống k&ecirc; v&agrave; nghi&ecirc;n cứu đ&aacute;p ứng y&ecirc;u cầu b&aacute;o c&aacute;o v&agrave;/hoặc duy tr&igrave; sổ s&aacute;ch nội bộ hoặc theo quy chế;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">p. để thực hiện quy tr&igrave;nh t&igrave;m hiểu v&agrave; x&aacute;c minh hoặc c&aacute;c hoạt động s&agrave;ng lọc kh&aacute;c (bao gồm kiểm tra l&yacute; lịch) tu&acirc;n thủ c&aacute;c nghĩa vụ theo quy định ph&aacute;p luật hoặc quản l&yacute; hoặc c&aacute;c thủ tục kiểm so&aacute;t rủi ro của ch&uacute;ng t&ocirc;i, c&oacute; thể được ph&aacute;p luật y&ecirc;u cầu hoặc c&oacute; thể đ&atilde; được ch&uacute;ng t&ocirc;i &aacute;p dụng;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">q. để kiểm tra C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i hoặc hoạt động của Shopee;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">r. để ngăn chặn hoặc điều tra bất kỳ hoạt động gian lận, phi ph&aacute;p, thiếu s&oacute;t hay h&agrave;nh vi sai tr&aacute;i n&agrave;o, cho d&ugrave; đ&atilde; diễn ra hay chưa, c&oacute; li&ecirc;n quan đến việc bạn sử dụng C&aacute;c Dịch Vụ của ch&uacute;ng t&ocirc;i hay kh&ocirc;ng hay bất kỳ vấn đề n&agrave;o ph&aacute;t sinh từ quan hệ của bạn với ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">s. để lưu trữ, lập m&aacute;y chủ, sao lưu (cho d&ugrave; l&agrave; v&igrave; mục đ&iacute;ch kh&ocirc;i phục sau thảm họa hoặc mục đ&iacute;ch kh&aacute;c) đối với dữ liệu c&aacute; nh&acirc;n của bạn;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">t. để xử l&yacute; v&agrave;/hoặc tạo thuận tiện cho một giao dịch t&agrave;i sản kinh doanh hoặc một giao dịch t&agrave;i sản kinh doanh tiềm năng, trường hợp giao dịch đ&oacute; li&ecirc;n quan đến Shopee như một b&ecirc;n tham gia hoặc chỉ li&ecirc;n quan đến một c&ocirc;ng ty hay c&ocirc;ng ty li&ecirc;n kết của Shopee như một b&ecirc;n tham gia hoặc li&ecirc;n quan đến Shopee v&agrave;/hoặc bất kỳ một hay nhiều c&ocirc;ng ty hoặc c&ocirc;ng ty li&ecirc;n kết của Shopee như (c&aacute;c) b&ecirc;n tham gia, v&agrave; c&oacute; thể c&oacute; c&aacute;c tổ chức b&ecirc;n thứ ba kh&aacute;c tham gia giao dịch như thế. &quot;Giao dịch t&agrave;i sản kinh doanh&quot; l&agrave; c&aacute;c giao dịch mua, b&aacute;n, cho thu&ecirc;, s&aacute;p nhập, hợp nhất hoặc bất kỳ hoạt động mua lại, thanh l&yacute; hay t&agrave;i trợ n&agrave;o của một tổ chức hoặc một phần của một tổ chức hoặc của bất kỳ hoạt động kinh doanh hay t&agrave;i sản n&agrave;o của một tổ chức; v&agrave;/hoặc</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">u. bất kỳ mục đ&iacute;ch n&agrave;o m&agrave; ch&uacute;ng t&ocirc;i th&ocirc;ng b&aacute;o cho bạn tại thời điểm xin sự cho ph&eacute;p của bạn.</span></span></span></span></p>
//
//<p style="margin-left:90px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">(gọi chung l&agrave; &ldquo;<strong>C&aacute;c Mục Đ&iacute;ch</strong>&rdquo;).</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">7.2. V&igrave; C&aacute;c Mục Đ&iacute;ch m&agrave; ch&uacute;ng t&ocirc;i sẽ/c&oacute; thể thu thập, sử dụng, tiết lộ hoặc xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn phụ thuộc v&agrave;o ho&agrave;n cảnh hiện c&oacute;, mục đ&iacute;ch đ&oacute; c&oacute; thể kh&ocirc;ng xuất hiện b&ecirc;n tr&ecirc;n. Tuy nhi&ecirc;n, ch&uacute;ng t&ocirc;i sẽ th&ocirc;ng b&aacute;o cho bạn biết mục đ&iacute;ch kh&aacute;c đ&oacute; tại thời điểm xin sự cho ph&eacute;p của bạn, trừ phi việc xử l&yacute; dữ liệu &aacute;p dụng m&agrave; kh&ocirc;ng c&oacute; sự đồng &yacute; của bạn l&agrave; được ph&eacute;p theo c&aacute;c quy định của ph&aacute;p luật về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n hoặc theo quy định ph&aacute;p luật.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>8.</strong><strong>&nbsp;</strong><strong>SHOPEE BẢO VỆ V&Agrave; LƯU TRỮ TH&Ocirc;NG TIN KH&Aacute;CH H&Agrave;NG BẰNG C&Aacute;CH N&Agrave;O</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">8.1. Ch&uacute;ng t&ocirc;i thực hiện c&aacute;c biện ph&aacute;p bảo mật kh&aacute;c nhau v&agrave; lu&ocirc;n nỗ lực để đảm bảo sự an to&agrave;n của dữ liệu c&aacute; nh&acirc;n của bạn tr&ecirc;n c&aacute;c hệ thống của ch&uacute;ng t&ocirc;i. Dữ liệu c&aacute; nh&acirc;n của người d&ugrave;ng được lưu trữ đằng sau c&aacute;c mạng bảo mật v&agrave; chỉ c&oacute; thể được truy cập bởi một số nh&acirc;n vi&ecirc;n c&oacute; quyền truy cập đặc biệt đến c&aacute;c hệ thống của ch&uacute;ng t&ocirc;i.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">8.2. Ch&uacute;ng t&ocirc;i sẽ duy tr&igrave; dữ liệu c&aacute; nh&acirc;n tu&acirc;n theo c&aacute;c quy định của ph&aacute;p luật về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n v&agrave;/hoặc c&aacute;c điều luật hiện h&agrave;nh kh&aacute;c. C&oacute; nghĩa l&agrave;, ch&uacute;ng t&ocirc;i sẽ hủy hoặc x&oacute;a th&ocirc;ng tin nhận dạng ra khỏi dữ liệu c&aacute; nh&acirc;n của bạn khi ch&uacute;ng t&ocirc;i c&oacute; l&yacute; do hợp l&yacute; để x&aacute;c định rằng (i) việc lưu giữ dữ liệu c&aacute; nh&acirc;n đ&oacute; kh&ocirc;ng c&ograve;n phục vụ mục đ&iacute;ch thu thập dữ liệu c&aacute; nh&acirc;n đ&oacute; nữa; (ii) việc lưu giữ kh&ocirc;ng c&ograve;n cần thiết cho bất kỳ mục đ&iacute;ch hợp ph&aacute;p hay mục đ&iacute;ch kinh doanh n&agrave;o v&agrave; (iii) kh&ocirc;ng c&ograve;n c&aacute;c lợi &iacute;ch hợp ph&aacute;p n&agrave;o kh&aacute;c để tiếp tục lưu giữ c&aacute;c dữ liệu c&aacute; nh&acirc;n n&agrave;y. Nếu bạn ngưng sử dụng Nền tảng của ch&uacute;ng t&ocirc;i, hoặc quyền của bạn được sử dụng Nền tảng v&agrave;/hoặc C&aacute;c Dịch Vụ bị chấm dứt hoặc hủy bỏ, ch&uacute;ng t&ocirc;i c&oacute; thể tiếp tục lưu, sử dụng v&agrave;/hoặc tiết lộ dữ liệu c&aacute; nh&acirc;n của bạn tu&acirc;n theo Ch&iacute;nh s&aacute;ch bảo mật n&agrave;y v&agrave; c&aacute;c nghĩa vụ của ch&uacute;ng t&ocirc;i theo c&aacute;c quy định của ph&aacute;p luật về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n. T&ugrave;y thuộc v&agrave;o quy định của ph&aacute;p luật, ch&uacute;ng t&ocirc;i c&oacute; thể ti&ecirc;u hủy dữ liệu c&aacute; nh&acirc;n của bạn một c&aacute;ch an to&agrave;n m&agrave; kh&ocirc;ng cần th&ocirc;ng b&aacute;o trước cho bạn.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>9.</strong><strong>&nbsp;</strong><strong>DOIDO C&Oacute; TIẾT LỘ TH&Ocirc;NG TIN THU THẬP TỪ NGƯỜI TRUY CẬP HAY KH&Ocirc;NG?</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">9.1. Trong qu&aacute; tr&igrave;nh thực hiện hoạt động kinh doanh, ch&uacute;ng t&ocirc;i sẽ/c&oacute; thể cần phải tiết lộ dữ liệu c&aacute; nh&acirc;n của bạn cho c&aacute;c nh&agrave; cung cấp dịch vụ b&ecirc;n thứ ba, đại l&yacute; v&agrave;/hoặc c&aacute;c c&ocirc;ng ty li&ecirc;n kết hoặc c&ocirc;ng ty li&ecirc;n quan của ch&uacute;ng t&ocirc;i, v&agrave;/hoặc c&aacute;c b&ecirc;n thứ ba kh&aacute;c, v&igrave; một hay nhiều Mục Đ&iacute;ch n&oacute;i tr&ecirc;n, v&agrave; việc tiết lộ n&agrave;y sẽ được thực hiện theo đ&uacute;ng tr&igrave;nh tự v&agrave; quy định của ph&aacute;p luật hiện h&agrave;nh. C&aacute;c nh&agrave; cung cấp dịch vụ b&ecirc;n thứ ba, đại l&yacute; v&agrave;/hoặc c&aacute;c c&ocirc;ng ty li&ecirc;n kết hoặc c&ocirc;ng ty li&ecirc;n quan v&agrave;/hoặc c&aacute;c b&ecirc;n thứ ba kh&aacute;c như thế sẽ xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn hoặc thay mặt ch&uacute;ng t&ocirc;i hoặc kh&aacute;c, v&igrave; một hoặc nhiều Mục Đ&iacute;ch n&oacute;i tr&ecirc;n. C&aacute;c b&ecirc;n thứ ba như thế bao gồm:</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">a. c&ocirc;ng ty con, c&ocirc;ng ty li&ecirc;n kết v&agrave; c&ocirc;ng ty li&ecirc;n quan của ch&uacute;ng t&ocirc;i;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">b. nh&agrave; thầu, đại l&yacute;, nh&agrave; cung cấp dịch vụ v&agrave; c&aacute;c b&ecirc;n thứ ba kh&aacute;c m&agrave; ch&uacute;ng t&ocirc;i thu&ecirc; để hỗ trợ hoặc bổ sung cho hoạt động kinh doanh của ch&uacute;ng t&ocirc;i. Những b&ecirc;n n&agrave;y bao gồm, nhưng kh&ocirc;ng giới hạn ở những b&ecirc;n cung cấp c&aacute;c dịch vụ quản trị hoặc c&aacute;c dịch vụ kh&aacute;c cho ch&uacute;ng t&ocirc;i chẳng hạn như c&ocirc;ng ty bưu ch&iacute;nh, c&ocirc;ng ty viễn th&ocirc;ng, c&ocirc;ng ty c&ocirc;ng nghệ th&ocirc;ng tin, c&aacute;c tổ chức hoạt động thương mại điện tử, v&agrave; trung t&acirc;m dữ liệu;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">c. người mua hoặc người thừa nhiệm kh&aacute;c trong trường hợp s&aacute;p nhập, tho&aacute;i vốn, t&aacute;i cơ cấu, t&aacute;i tổ chức, giải thể hoặc b&aacute;n hay chuyển nhượng một phần hoặc tất cả t&agrave;i sản của Shopee, cho d&ugrave; l&agrave; vấn đề đang diễn ra hay đang trong thủ tục ph&aacute; sản, thanh l&yacute; hoặc thủ tục tương tự, trong đ&oacute; dữ liệu c&aacute; nh&acirc;n Shopee lưu giữ về người d&ugrave;ng của ch&uacute;ng t&ocirc;i nằm trong c&aacute;c t&agrave;i sản được chuyển nhượng; hoặc cho một b&ecirc;n đối t&aacute;c trong một giao dịch t&agrave;i sản kinh doanh m&agrave; Shopee hoặc bất kỳ c&ocirc;ng ty li&ecirc;n kết hay c&ocirc;ng ty li&ecirc;n quan n&agrave;o của n&oacute; c&oacute; tham gia giao dịch; v&agrave;</span></span></span></span></p>
//
//<p style="margin-left:78px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">d. b&ecirc;n thứ ba m&agrave; ch&uacute;ng t&ocirc;i tiết lộ th&ocirc;ng tin v&igrave; một trong c&aacute;c Mục Đ&iacute;ch v&agrave; c&aacute;c b&ecirc;n thứ ba đ&oacute; ngược lại họ sẽ thu thập v&agrave; xử l&yacute; dữ liệu c&aacute; nh&acirc;n của bạn v&igrave; một hoặc nhiều Mục Đ&iacute;ch</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">9.2. Trường hợp n&agrave;y c&oacute; thể y&ecirc;u cầu, ngo&agrave;i c&aacute;c vấn đề kh&aacute;c, chia sẻ th&ocirc;ng tin thống k&ecirc; v&agrave; nh&acirc;n khẩu học về Người D&ugrave;ng cũng như việc sử dụng C&aacute;c Dịch Vụ của người d&ugrave;ng với đối t&aacute;c cung cấp dịch vụ quảng c&aacute;o v&agrave; lập tr&igrave;nh. Ch&uacute;ng t&ocirc;i cũng sẽ chia sẻ th&ocirc;ng tin thống k&ecirc; v&agrave; th&ocirc;ng tin nh&acirc;n khẩu học về người d&ugrave;ng của ch&uacute;ng t&ocirc;i v&agrave; việc họ sử dụng C&aacute;c Dịch Vụ với c&aacute;c nh&agrave; cung cấp dịch vụ quảng c&aacute;o v&agrave; lập tr&igrave;nh. Trường hợp n&agrave;y sẽ kh&ocirc;ng bao gồm bất kỳ th&ocirc;ng tin n&agrave;o c&oacute; thể được sử dụng để x&aacute;c định danh t&iacute;nh cụ thể của bạn hoặc tiết lộ th&ocirc;ng tin c&aacute; nh&acirc;n về bạn.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">9.3. Để tr&aacute;nh nghi ngờ, trong trường hợp c&aacute;c quy định của ph&aacute;p luật về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n hoặc c&aacute;c điều luật hiện h&agrave;nh kh&aacute;c cho ph&eacute;p một tổ chức chẳng hạn như ch&uacute;ng t&ocirc;i thu thập, sử dụng hoặc tiết lộ dữ liệu c&aacute; nh&acirc;n của bạn m&agrave; kh&ocirc;ng cần sự đồng &yacute; của bạn, sự cho ph&eacute;p như thế của ph&aacute;p luật sẽ tiếp tục &aacute;p dụng.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">9.4. C&aacute;c b&ecirc;n thứ ba c&oacute; thể chặn hoặc truy cập tr&aacute;i ph&eacute;p dữ liệu c&aacute; nh&acirc;n được gửi đến hoặc c&oacute; tr&ecirc;n trang web, c&aacute;c c&ocirc;ng nghệ c&oacute; thể hoạt động kh&ocirc;ng ch&iacute;nh x&aacute;c hoặc kh&ocirc;ng hoạt động như dự kiến, hoặc c&oacute; người c&oacute; thể truy cập, lạm dụng hoặc sử dụng sai tr&aacute;i th&ocirc;ng tin m&agrave; kh&ocirc;ng phải lỗi của ch&uacute;ng t&ocirc;i. Tuy nhi&ecirc;n ch&uacute;ng t&ocirc;i sẽ triển khai c&aacute;c biện ph&aacute;p bảo mật hợp l&yacute; để bảo vệ dữ liệu c&aacute; nh&acirc;n của bạn theo quy định của c&aacute;c quy định của ph&aacute;p luật về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n; tuy nhi&ecirc;n kh&ocirc;ng thể đảm bảo sự bảo mật tuyệt đối chẳng hạn như trường hợp tiết lộ tr&aacute;i ph&eacute;p ph&aacute;t sinh từ hoạt động tin tặc v&igrave; &yacute; đồ xấu hoặc phức tạp của c&aacute;c nội dung c&oacute; độc kh&ocirc;ng phải lỗi của ch&uacute;ng t&ocirc;i.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">9.5. Shopee cho ph&eacute;p bạn chia sẻ video từ YouTube trong t&iacute;nh năng Shopee Livestream (&ldquo;Nội Dung YouTube&rdquo;). Về mặt kỹ thuật, Shopee sử dụng T&iacute;nh Năng YouTube API của ch&iacute;nh YouTube. Th&ocirc;ng qua việc chia sẻ Nội Dung YouTube, bạn theo đ&acirc;y đồng &yacute; chịu sự điều chỉnh của Ch&iacute;nh S&aacute;ch Bảo Mật của YouTube (<a href="http://www.google.com/policies/privacy" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>http://www.google.com/policies/privacy</u></a>).</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>10.</strong><strong>&nbsp;</strong><strong>TH&Ocirc;NG TIN VỀ TRẺ EM</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">C&aacute;c Dịch Vụ n&agrave;y kh&ocirc;ng d&agrave;nh cho trẻ em dưới 13 tuổi. Ch&uacute;ng t&ocirc;i kh&ocirc;ng cố t&igrave;nh thu thập hay lưu giữ bất kỳ dữ liệu c&aacute; nh&acirc;n hay th&ocirc;ng tin kh&ocirc;ng nhận dạng c&aacute; nh&acirc;n n&agrave;o của bất kỳ ai dưới 13 tuổi, bất kỳ phần n&agrave;o của Nền tảng của ch&uacute;ng t&ocirc;i hoặc C&aacute;c Dịch Vụ kh&aacute;c cũng kh&ocirc;ng d&agrave;nh cho trẻ em dưới 13 tuổi. Bố/mẹ hoặc người gi&aacute;m hộ của trẻ em dưới 13 tuổi vui l&ograve;ng gi&aacute;m s&aacute;t v&agrave; đảm bảo th&ocirc;ng tin c&aacute; nh&acirc;n của trẻ dưới 13 tuổi m&agrave; m&igrave;nh đang gi&aacute;m hộ kh&ocirc;ng đăng tải th&ocirc;ng tin c&aacute; nh&acirc;n cho Shopee. Trong trường hợp th&ocirc;ng tin c&aacute; nh&acirc;n của của trẻ em dưới 13 tuổi do qu&yacute; phụ huynh gi&aacute;m hộ được cung cấp cho Shopee, Bố/mẹ hoặc người gi&aacute;m hộ theo đồng &yacute; với việc xử l&yacute; th&ocirc;ng tin của trẻ em dưới 13 tuổi c&oacute; li&ecirc;n quan, v&agrave; đồng &yacute; chịu sự điều chỉnh của Ch&iacute;nh S&aacute;ch n&agrave;y thay mặt cho người được gi&aacute;m hộ. Ch&uacute;ng t&ocirc;i sẽ kh&oacute;a bất kỳ t&agrave;i khoản n&agrave;o chỉ được sử dụng bởi đối tượng trẻ em như vậy v&agrave; sẽ gỡ v&agrave;/hoặc x&oacute;a bất kỳ dữ liệu c&aacute; nh&acirc;n n&agrave;o m&agrave; ch&uacute;ng t&ocirc;i cho l&agrave; đ&atilde; được gửi bởi bất kỳ trẻ em n&agrave;o dưới 13 tuổi.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>11.</strong><strong>&nbsp;</strong><strong>TH&Ocirc;NG TIN THU THẬP BỞI C&Aacute;C B&Ecirc;N THỨ BA</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">11.1. Nền tảng của ch&uacute;ng t&ocirc;i sử dụng Google Analytics, một dịch vụ ph&acirc;n t&iacute;ch web được cung cấp bởi Google, Inc. (&quot;Google&quot;). Google Analytics sử dụng cookie, l&agrave; c&aacute;c tập tin văn bản được đặt v&agrave;o thiết bị của bạn, để gi&uacute;p Nền tảng ph&acirc;n t&iacute;ch c&aacute;ch thức người d&ugrave;ng sử dụng Nền tảng của ch&uacute;ng t&ocirc;i. Th&ocirc;ng tin được tạo bởi cookie về việc bạn sử dụng Nền tảng (bao gồm địa chỉ IP của bạn) sẽ được gửi đến v&agrave; lưu bởi Google tr&ecirc;n c&aacute;c m&aacute;y chủ tại Hoa Kỳ. Google sẽ sử dụng th&ocirc;ng tin n&agrave;y để đ&aacute;nh gi&aacute; việc bạn sử dụng Nền tảng của ch&uacute;ng t&ocirc;i, soạn b&aacute;o c&aacute;o về hoạt động trang web d&agrave;nh cho c&aacute;c nh&agrave; điều h&agrave;nh trang web v&agrave; cung cấp c&aacute;c dịch vụ kh&aacute;c li&ecirc;n quan đến hoạt động trang web v&agrave; việc sử dụng Internet. Google cũng c&oacute; thể gửi th&ocirc;ng tin n&agrave;y cho c&aacute;c b&ecirc;n thứ ba trong trường hợp luật ph&aacute;p c&oacute; quy định như thế, hoặc trường hợp c&aacute;c b&ecirc;n thứ ba đ&oacute; xử l&yacute; th&ocirc;ng tin thay mặt Google. Google sẽ kh&ocirc;ng li&ecirc;n kết địa chỉ IP của bạn với bất kỳ dữ liệu n&agrave;o kh&aacute;c m&agrave; Google nắm giữ.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">11.2. Ch&uacute;ng t&ocirc;i, v&agrave; c&aacute;c b&ecirc;n thứ ba, c&oacute; thể thỉnh thoảng cung cấp c&aacute;c bản tải về ứng dụng phần mềm cho bạn sử dụng bởi Nền tảng hoặc th&ocirc;ng qua C&aacute;c Dịch Vụ. Những ứng dụng n&agrave;y c&oacute; thể truy cập ri&ecirc;ng, v&agrave; cho ph&eacute;p một b&ecirc;n thứ ba xem, th&ocirc;ng tin nhận dạng của bạn, chẳng hạn như t&ecirc;n, ID người d&ugrave;ng của bạn, Địa chỉ IP của thiết bị của bạn hoặc th&ocirc;ng tin kh&aacute;c chẳng hạn như game bạn đang chơi trong bất kỳ phi&ecirc;n truy cập cụ thể n&agrave;o, v&agrave; bất kỳ cookie n&agrave;o trước đ&acirc;y bạn c&oacute; thể đ&atilde; c&agrave;i đặt hoặc đ&atilde; được c&agrave;i đặt cho bạn bởi một ứng dụng phần mềm hoặc trang web của b&ecirc;n thứ ba. Ngo&agrave;i ra, c&aacute;c ứng dụng n&agrave;y c&oacute; thể y&ecirc;u cầu bạn cung cấp th&ecirc;m th&ocirc;ng tin trực tiếp cho c&aacute;c b&ecirc;n thứ ba. C&aacute;c sản phẩm hoặc dịch vụ của b&ecirc;n thứ ba được cung cấp th&ocirc;ng qua c&aacute;c ứng dụng n&agrave;y kh&ocirc;ng thuộc sở hữu hay quyền kiểm so&aacute;t của Shopee. Bạn n&ecirc;n đọc c&aacute;c điều khoản v&agrave; c&aacute;c ch&iacute;nh s&aacute;ch kh&aacute;c được c&ocirc;ng bố bởi c&aacute;c b&ecirc;n thứ ba đ&oacute; tr&ecirc;n trang web của họ hoặc nơi kh&aacute;c.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>12.</strong><strong>&nbsp;</strong><strong>LOẠI TRỪ TR&Aacute;CH NHIỆM VỀ NGHĨA VỤ BẢO MẬT V&Agrave; C&Aacute;C TRANG WEB B&Ecirc;N THỨ BA</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">12.1. CH&Uacute;NG T&Ocirc;I KH&Ocirc;NG ĐẢM BẢO T&Iacute;NH BẢO MẬT ĐỐI VỚI DỮ LIỆU C&Aacute; NH&Acirc;N V&Agrave;/HOẶC TH&Ocirc;NG TIN KH&Aacute;C M&Agrave; BẠN CUNG CẤP TR&Ecirc;N C&Aacute;C TRANG WEB CỦA B&Ecirc;N THỨ BA. Ch&uacute;ng t&ocirc;i thực hiện c&aacute;c biện ph&aacute;p bảo mật kh&aacute;c nhau để duy tr&igrave; sự an to&agrave;n của dữ liệu c&aacute; nh&acirc;n của bạn m&agrave; ch&uacute;ng t&ocirc;i lưu giữ hoặc kiểm so&aacute;t. Dữ liệu c&aacute; nh&acirc;n của bạn được lưu đằng sau c&aacute;c mạng bảo mật v&agrave; chỉ c&oacute; thể được truy cập bởi một số c&aacute; nh&acirc;n giới hạn c&oacute; quyền truy cập đặc biệt đến c&aacute;c hệ thống của ch&uacute;ng t&ocirc;i, v&agrave; đ&atilde; được y&ecirc;u cầu bảo mật dữ liệu c&aacute; nh&acirc;n đ&oacute;. Khi bạn đặt h&agrave;ng hoặc truy cập dữ liệu c&aacute; nh&acirc;n của bạn, ch&uacute;ng t&ocirc;i đề nghị sử dụng một m&aacute;y chủ bảo mật. Tất cả dữ liệu c&aacute; nh&acirc;n hoặc th&ocirc;ng tin c&aacute; nh&acirc;n bạn cung cấp sẽ được m&atilde; h&oacute;a v&agrave;o c&aacute;c cơ sở dữ liệu của ch&uacute;ng t&ocirc;i để chỉ được truy cập như m&ocirc; tả b&ecirc;n tr&ecirc;n.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">12.2. Nhằm cung cấp cho bạn gi&aacute; trị gia tăng, ch&uacute;ng t&ocirc;i c&oacute; thể chọn c&aacute;c trang web hoặc ứng dụng hoặc dịch vụ của b&ecirc;n thứ ba kh&aacute;c nhau để li&ecirc;n kết, v&agrave; đ&oacute;ng khung b&ecirc;n trong Nền tảng. Ch&uacute;ng t&ocirc;i cũng c&oacute; thể tham gia c&aacute;c quan hệ c&ugrave;ng tiếp thị v&agrave; c&aacute;c quan hệ kh&aacute;c để cung cấp dịch vụ thương mại điện tử v&agrave; c&aacute;c dịch vụ v&agrave; t&iacute;nh năng kh&aacute;c cho kh&aacute;ch truy cập. Những trang được li&ecirc;n kết n&agrave;y c&oacute; c&aacute;c ch&iacute;nh s&aacute;ch về quyền ri&ecirc;ng tư cũng như c&aacute;c biện ph&aacute;p bảo mật ri&ecirc;ng v&agrave; độc lập. Ngay cả khi b&ecirc;n thứ ba đ&oacute; c&oacute; li&ecirc;n kết với ch&uacute;ng t&ocirc;i, ch&uacute;ng t&ocirc;i cũng kh&ocirc;ng kiểm so&aacute;t c&aacute;c trang web/ứng dụng/dịch vụ được li&ecirc;n kết n&agrave;y, mỗi trang đ&oacute; c&oacute; c&aacute;c phương ph&aacute;p bảo vệ quyền ri&ecirc;ng tư v&agrave; thu thập dữ liệu ri&ecirc;ng biệt, độc lập với ch&uacute;ng t&ocirc;i. Dữ liệu thu thập bởi c&aacute;c đối t&aacute;c c&ugrave;ng tiếp thị của ch&uacute;ng t&ocirc;i hoặc c&aacute;c trang web/ứng dụng/dịch vụ của b&ecirc;n thứ ba (ngay cả khi được cung cấp tr&ecirc;n hoặc th&ocirc;ng qua Nền tảng của ch&uacute;ng t&ocirc;i) c&oacute; thể kh&ocirc;ng được ch&uacute;ng t&ocirc;i tiếp cận v&agrave;/hoặc lưu giữ.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">12.3. Do đ&oacute; ch&uacute;ng t&ocirc;i kh&ocirc;ng chịu tr&aacute;ch nhiệm hay tr&aacute;ch nhiệm ph&aacute;p l&yacute; đối với nội dung, c&aacute;c biện ph&aacute;p bảo mật (hoặc sự thiếu biện ph&aacute;p bảo mật) v&agrave; c&aacute;c hoạt động của c&aacute;c trang web/ứng dụng/dịch vụ được li&ecirc;n kết n&agrave;y. Những trang web/ứng dụng/dịch vụ được li&ecirc;n kết n&agrave;y chỉ v&igrave; sự thuận tiện cho bạn v&agrave; do đ&oacute; bạn tự chịu tr&aacute;ch nhiệm khi truy cập ch&uacute;ng. Tuy nhi&ecirc;n, ch&uacute;ng t&ocirc;i t&igrave;m c&aacute;ch bảo vệ t&iacute;nh to&agrave;n vẹn của Nền tảng của ch&uacute;ng t&ocirc;i v&agrave; c&aacute;c li&ecirc;n kết được đặt tr&ecirc;n từng trang web đ&oacute; v&agrave; do đ&oacute; ch&uacute;ng t&ocirc;i hoan ngh&ecirc;nh &yacute; kiến phản hồi về c&aacute;c trang web được li&ecirc;n kết n&agrave;y (bao gồm nếu một trang web cụ thể kh&ocirc;ng hoạt động).</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">&nbsp;</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>13.</strong><strong>&nbsp;</strong><strong>BẠN C&Oacute; THỂ R&Uacute;T T&Ecirc;N, X&Oacute;A T&Ecirc;N, Y&Ecirc;U CẦU TRUY CẬP HOẶC ĐIỀU CHỈNH TH&Ocirc;NG TIN BẠN Đ&Atilde; CUNG CẤP CHO CH&Uacute;NG T&Ocirc;I BẰNG C&Aacute;CH N&Agrave;O?</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><em>R&uacute;t Lại Sự Đồng &Yacute;</em></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">13.1. Bạn c&oacute; thể r&uacute;t lại sự đồng &yacute; cho ph&eacute;p thu thập, sử dụng v&agrave;/hoặc tiết lộ dữ liệu c&aacute; nh&acirc;n của bạn m&agrave; ch&uacute;ng t&ocirc;i đang lưu giữ hoặc kiểm so&aacute;t bằng c&aacute;ch gửi email cho Bộ phận Bảo Vệ Dữ Liệu C&aacute; Nh&acirc;n của ch&uacute;ng t&ocirc;i tại địa chỉ email&nbsp;<a href="mailto:dpo.vn@Shopee.com" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>dpo.vn@Shopee.com</u></a>&nbsp;hoặc qua&nbsp;<a href="https://help.shopee.vn/vn/s/contactusform" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>Đ&Acirc;Y</u></a>, v&agrave; ch&uacute;ng t&ocirc;i sẽ xử l&yacute; c&aacute;c y&ecirc;u cầu n&agrave;y theo Ch&iacute;nh S&aacute;ch Bảo Mật cũng như quy định ph&aacute;p luật c&oacute; li&ecirc;n quan.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">13.2. Tuy nhi&ecirc;n, việc bạn r&uacute;t lại sự đồng &yacute; c&oacute; thể c&oacute; nghĩa l&agrave; ch&uacute;ng t&ocirc;i sẽ kh&ocirc;ng thể tiếp tục cung cấp C&aacute;c Dịch Vụ cho bạn, v&agrave; ch&uacute;ng t&ocirc;i c&oacute; thể cần phải chấm dứt quan hệ hiện tại của bạn v&agrave;/hoặc hợp đồng của bạn với ch&uacute;ng t&ocirc;i.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">13.3 Khi bạn chia sẻ Nội Dung YouTube, b&ecirc;n cạnh việc r&uacute;t lại sự đồng &yacute; bằng c&aacute;ch gửi email cho ch&uacute;ng t&ocirc;i theo Khoản 13.1, bạn c&oacute; thể hủy cho ph&eacute;p truy cập của Shopee đến c&aacute;c th&ocirc;ng tin c&aacute; nh&acirc;n của bạn th&ocirc;ng qua t&ugrave;y chọn bảo mật của Google tại&nbsp;<a href="https://security.google.com/settings/security/permissions" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>https://security.google.com/settings/security/permissions</u></a>.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><em>Y&ecirc;u Cầu Truy Cập đến hoặc Sửa Dữ Liệu C&aacute; Nh&acirc;n</em></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">13.4. Nếu bạn đ&atilde; đăng k&yacute; một t&agrave;i khoản với ch&uacute;ng t&ocirc;i, c&aacute; nh&acirc;n bạn c&oacute; thể truy cập v&agrave;/hoặc sửa dữ liệu c&aacute; nh&acirc;n của bạn m&agrave; ch&uacute;ng t&ocirc;i đang lưu giữ hoặc kiểm so&aacute;t th&ocirc;ng qua trang Thiết Lập T&agrave;i Khoản hoặc nh&atilde;n tr&ecirc;n Nền tảng. Nếu bạn chưa đăng k&yacute; t&agrave;i khoản với ch&uacute;ng t&ocirc;i, c&aacute; nh&acirc;n bạn c&oacute; thể y&ecirc;u cầu truy cập v&agrave;/hoặc sửa dữ liệu c&aacute; nh&acirc;n của bạn m&agrave; ch&uacute;ng t&ocirc;i đang lưu giữ hoặc kiểm so&aacute;t bằng c&aacute;ch gửi y&ecirc;u cầu bằng văn bản cho ch&uacute;ng t&ocirc;i. Ch&uacute;ng t&ocirc;i sẽ cần c&oacute; đủ th&ocirc;ng tin từ bạn để x&aacute;c định danh t&iacute;nh của bạn cũng như bản chất y&ecirc;u cầu của bạn để c&oacute; thể giải quyết y&ecirc;u cầu của bạn. Do đ&oacute;, vui l&ograve;ng gửi y&ecirc;u cầu bằng văn bản của bạn bằng c&aacute;ch gửi email cho nh&acirc;n vi&ecirc;n Quản l&yacute; dữ liệu của ch&uacute;ng t&ocirc;i tại&nbsp;<a href="https://help.shopee.vn/vn/s/contactusform" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>Đ&Acirc;Y</u></a>.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">13.5. Ch&uacute;ng t&ocirc;i c&oacute; thể t&iacute;nh một khoản ph&iacute; hợp l&yacute; cho bạn để giải quyết v&agrave; xử l&yacute; y&ecirc;u cầu truy cập dữ liệu c&aacute; nh&acirc;n của bạn. Nếu ch&uacute;ng t&ocirc;i c&oacute; t&iacute;nh ph&iacute;, ch&uacute;ng t&ocirc;i sẽ cung cấp cho bạn ước t&iacute;nh lệ ph&iacute; bằng văn bản. Vui l&ograve;ng lưu &yacute; rằng ch&uacute;ng t&ocirc;i kh&ocirc;ng buộc phải đ&aacute;p ứng hay giải quyết y&ecirc;u cầu truy cập của bạn trừ phi bạn đ&atilde; đồng &yacute; đ&oacute;ng ph&iacute;.</span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">13.6. Ch&uacute;ng t&ocirc;i bảo lưu quyền từ chối sửa dữ liệu c&aacute; nh&acirc;n của bạn theo c&aacute;c quy định của ph&aacute;p luật về bảo vệ b&iacute; mật th&ocirc;ng tin c&aacute; nh&acirc;n, trường hợp c&aacute;c điều luật đ&oacute; y&ecirc;u cầu v&agrave;/hoặc cho ph&eacute;p một tổ chức từ chối sửa dữ liệu c&aacute; nh&acirc;n trong c&aacute;c trường hợp như thế.</span></span></span></span></p>
//
//<p style="margin-left:24px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><strong>14.</strong><strong>&nbsp;</strong><strong>THẮC MẮC, QUAN NGẠI HOẶC KHIẾU NẠI? LI&Ecirc;N HỆ VỚI CH&Uacute;NG T&Ocirc;I</strong></span></span></span></span></p>
//
//<p style="margin-left:36px; text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">Nếu bạn c&oacute; bất kỳ thắc mắc hoặc khiếu nại n&agrave;o về c&aacute;c phương ph&aacute;p bảo vệ quyền ri&ecirc;ng tư của ch&uacute;ng t&ocirc;i vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i tại&nbsp;<a href="https://help.shopee.vn/vn/s/contactusform" style="box-sizing:border-box; background:0px 0px transparent; color:#428bca; text-decoration:none"><u>Đ&Acirc;Y</u></a>.</span></span></span></span></p>
//
//<p style="text-align:justify"><span style="font-size:14px"><span style="background-color:#ffffff"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial">&nbsp;</span></span></span></span></p>
//
//<p style="text-align:start"><span style="font-size:14px"><span style="color:#535258"><span style="font-family:&quot;B Koodak&quot;,&quot;X Koodak&quot;,Koodak,Arial"><span style="background-color:#ffffff"><strong>Bản C&acirc;̣p Nh&acirc;̣t ngày 21/01/2021.</strong></span></span></span></span></p>
//
//<div id="gtx-trans" style="left:73px; position:absolute; top:3933px">
//<div class="gtx-trans-icon">&nbsp;</div>',
                'titlePage' => 'html mau',
                'descriptionPage' => 'html mau',
                'keywordPage' => 'html mau',
                'created_at' => Carbon::create(2021, 8, 21, 21, 40, 16), //->diffForHumans(Carbon::now()),
                'updated_at' => Carbon::now()
            ]
        ]);
    }
}
